apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  labels:
    name: voting-app
    app: demo-app
      
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app
      app: demo-app
  
  template:
    metadata: 
      name: voting-app
      labels:
        name: voting-app
        app: demo-app

    spec:
      containers:
        - name: voting-app 
          image: kodekloud/examplevotingapp_vote:v1
          ports: 
            - containerPort: 80