apiVersion: v1
kind: Pod
metadata: 
  name: v-app
  labels:
    name: v-app
    app: demo-app

spec:
  containers:
    - name: v-app 
      image: kodekloud/examplevotingapp_vote:v1
      ports: 
        - containerPort: 80
