apiVersion: v1
kind: Service 
metadata:
  name: postgres
  labels:
    name: postgres-service
    app: demo-app

spec:
  ports:
    - port: 6379
      targetPort: 6379 

  selector:
    name: postgres-app
    app: demo-app