apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  labels:
    name: redis-app
    app: demo-app
      
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-app
      app: demo-app
  template:
    metadata: 
      name: redis-app
      labels:
        name: redis-app
        app: demo-app

    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
