apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  labels:
    name: result-app
    app: demo-app
      
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app
      app: demo-app
  
  template:
    metadata: 
      name: result-app
      labels:
        name: result-app
        app: demo-app

    spec:
      containers:
        - name: result
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80