apiVersion: v1
kind: Service 
metadata:
  name: result
  labels:
    name: result-service
    app: demo-app

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005

  selector:
    name: result-app
    app: demo-app