apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  labels:
    name: worker-app
    app: demo-app
      
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app
      app: demo-app
  
  template:
    metadata: 
      name: worker-app
      labels:
        name: worker-app
        app: demo-app

    spec:
      containers:
        - name: worker-app 
          image: kodekloud/examplevotingapp_worker:v2